language: go

go:
    - 1.8

env:
    global:
        - SSH_KEY="id_rsa"
        - GIT_NAME="purplepalmdash"
        - GIT_EMAIL="purplepalm@gmail.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="source"

branches:
    only:
        - source

git:
    submodules: false

before_install:
    - openssl aes-256-cbc -K $encrypted_5f0a10095440_key -iv $encrypted_5f0a10095440_iv -in `pwd`/id_rsa.enc -out id_rsa -d

install:
    - go get -u -v github.com/gohugoio/hugo

script:
    - cd $HOME/gopath/src/github.com/purplepalmdash/purplepalmdash.github.io && hugo version &&  hugo && ls -l public/

after_success:
    - echo "purplepalmdash.github.io" > ./public/CNAME
    - ./scripts/deploy.sh
