language: go

go:
    - 1.7

env:
    global:
        - SSH_KEY="id_rsa"
        - GIT_NAME="purplepalmdash"
        - GIT_EMAIL="purplepalm@gmail.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="source"
git:
    submodules: false

before_install:
    - openssl aes-256-cbc -K $encrypted_5f0a10095440_key -iv $encrypted_5f0a10095440_iv -in id_rsa.enc -out id_rsa -d

install:
    - go get -u -v github.com/kardianos/govendor
    - go get -u -v github.com/spf13/hugo
    - cd $GOPATH/src/github.com/spf13/hugo && govendor sync && go install
  

script:
    - cd $HOME/gopath/src/github.com/purplepalmdash/purplepalmdash.github.io && hugo

after_success:
    - echo "purplepalmdash.github.io" > ./public/CNAME
    - ./scripts/deploy.sh

