language: go

go:
    - 1.6

env:
    global:
        - SSH_KEY="id_rsa"
        - GIT_NAME="purplepalmdash"
        - GIT_EMAIL="purplepalm@gmail.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="source"
git:
    submodules: false

before_install:
    - openssl aes-256-cbc -K $encrypted_5f0a10095440_key -iv $encrypted_5f0a10095440_iv -in id_rsa.enc -out id_rsa -d

install:
    - go get -u -v github.com/spf13/hugo

script:
    - git https://github.com/rcoedo/hugo-steam-theme ./themes/hugo-steam-theme
    - hugo

after_success:
    - echo "purplepalmdash.github.io" > ./public/CNAME
    - ./scripts/deploy.sh

